# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 장철준
title: 공공기관 프로젝트 경험을 바탕으로 성장하는 개발자
email: jcj145@naver.com
# email_title: Email (Email title override)
phone: 010-6262-4318
address: 서울특별시 중랑구 중화동
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/증명사진.jpg
about_content: | # this will include new lines to allow paragraphs
  **최종학력**
  - 경남정보대학교 (2,3년제)
  - ICT컴퓨터계열
  - 최종학점 3.9
  - C, C#, Java, HTML, JavaScript, Linux, MySql 등 교육받음 

  **경력**
  - (주)에코누리시스템 에서 2년 2개월(2022.11 ~ 2024.12) 근무
  - 연구개발팀 사원으로 SI/SM 업무 진행

  **나의 스킬**
  - Java
  - Spring Framework, eGovFrameWork
  - JSP, JavaScript, HTML5, Ajax, CSS3
  - Mysql, Oracle, PostgreSql, Tibero, Cubrid
  - SVN, GitLab
  - Linux

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 목재정보서비스
        link: https://winz.forest.go.kr
        link_text: 목재정보서비스
        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
 #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
   #         icon: fab fa-github
   #         url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
            **프로젝트 참여기간**  
            - 구축사업 2차 2023.01.01 ~ 2023.11.21
            - 구축사업 3차 2024.08.19 ~ 2024.11.15
            - 유지관리 운영사업 2024.03 ~ 2024.12.27
            
            **사용된 기술**
            - eGovFramework3.10 (전자정부프레임워크)
            - Spring Security
            - Java 1.8
            - Mybatis
            - JSP, JavaScript, jQuery, CSS
            - DBMS (Postgresql, Tibero, Cubrid, Oracle)
            - Daum주소 API, 카카오맵 API, 간편인증 API
            - Linux, Jboss, Apache Tomcat 9.0
            - SVN, GibLab
            
            **기능 개발 담당 파트**
            - 국산목재의 탄소저장량 표시제도, 신기술 신청 및 증명서 발급 프로세스 개발
            - 국산목재 거래장터 한목꾸러미 개발
            - 한목디자인공모전 신청 및 결과등록 프로세스 개발
            - 공공개발지 벌채 등록 및 관리 개발
            - 목재문화체험장 조회 및 관리 개발
            - 공무원 IP접근 제어 및 공인인증서 로그인 기능 개발
            - SMS발송 공통기능 개발
            - 첨부파일관리 공통기능 개발

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
   content:
      - layout: left
       border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 목재자원관리시스템
#        link: https://winz.forest.go.kr
#        link_text: 목재정보서비스
        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
 #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
   #         icon: fab fa-github
   #         url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
            **프로젝트 참여기간**  
            - 목재자원관리시스템 운영 및 유지보수 2023.01 ~ 2024.12
            
            **사용된 기술**
            - eGovFramework3.10 (전자정부프레임워크)
            - Spring Security
            - Java
            - Mybatis
            - JSP, JavaScript, jQuery, CSS
            - DBMS (Tibero, Oracle)
            - SVN

  #- title: Experience
   # layout: list
    #content:
     # - layout: right
      #  title: Company name
       # sub_title: Job title
        #caption: Date Range (eg. November 2016 - present)
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
       # description: | # this will include new lines to allow paragraphs
         # Description of role
  #- title: Education
  #  layout: list
  #  content:
  #    - layout: top-right
  #      title: Institution name
  #      sub_title: Qualifications (eg. BA Performing Arts)
  #      caption: Date Range (eg. 2016 - 2019)
  #      quote: >
  #        Short institution or course description (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description of qualification
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#
#      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
